services:
  web:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: user 
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ./db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql  # SQL dosyasını mount ediyoruz

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: my_password
    ports:
      - "8081:80"
    depends_on:
      - db
      
volumes:
  db_data:
